### ISSUE TITLE
wordpressのDBをバックアップするシェルスクリプトを作成する

### ISSUE THREAD

**Issue by RVIRUS0817** [naoya0408/menta#11]
https://github.com/naoya0408/menta/issues/10

上記で動いたwordpressのDBをバックアップしましょう。

- 対象: 全てのデータベース
- シェルスクリプト
- 5日間のみ保存するようにする

**Comment by RVIRUS0817** [comment]
@naoya0408 
こちらブランチ切ってプルリクをお願いします。
まずは調べながらやっていきましょう。

**Comment by naoya0408** [comment]
@RVIRUS0817 
WordPressをバックアップするシェルスクリプトを作成しました。
確認よろしくお願いします！

**Comment by RVIRUS0817** [comment]
@naoya0408 
プルリクをお願いします。
あとそのスクリプトの挙動を確認したいので、それもプルリクに書いてください。
https://github.com/naoya0408/menta
あとmasterにpushしていますが、これはしないよう気をつけてください！

**Comment by naoya0408** [comment]
プルリクしました。
誤ってmasterにプッシュしてしまいました。
すみませんでした。

**Comment by RVIRUS0817** [comment]
こちらマージOKなのでクローズします。
